import { VehicleDefinition, Mission, Landmark, InteractiveShop } from '../types/game';

export const INITIAL_VEHICLES: VehicleDefinition[] = [
  {
    id: 'bmw_m13',
    name: 'BMW M13 Competition',
    category: 'supercar',
    description: 'High-performance Bavarian sports coupe with twin-turbo straight-six power, signature kidney grille, M quad exhausts, and competition dynamics.',
    topSpeed: 255,
    acceleration: 95,
    braking: 92,
    handling: 93,
    driftFactor: 0.88,
    weight: 1490,
    price: 0, // Starter car unlocked
    unlocked: true,
    color: '#0284c7', // Bavarian Estoril Blue
    accentColor: '#0f172a',
    soundPitch: 1.2,
  },
  {
    id: 'mustang_gt',
    name: 'Ford Mustang Shelby GT500',
    category: 'supercar',
    description: 'Supercharged 5.2L V8 muscle legend with iconic dual racing stripes, immense low-end torque, aggressive stance, and active valve exhaust notes.',
    topSpeed: 290,
    acceleration: 90,
    braking: 88,
    handling: 85,
    driftFactor: 0.95,
    weight: 1720,
    price: 8500,
    unlocked: true,
    color: '#0f3263', // Liquid Blue Metallic
    accentColor: '#ffffff',
    soundPitch: 0.82,
  },
  {
    id: 'tesla_plaid',
    name: 'Tesla Model S Plaid',
    category: 'sedan',
    description: 'Tri-motor electric sleeper sedan pushing 1,020 horsepower. Instantaneous electric torque, zero lag, minimal body grille, and futuristic yoke control feel.',
    topSpeed: 322,
    acceleration: 99,
    braking: 89,
    handling: 87,
    driftFactor: 0.58,
    weight: 2160,
    price: 15500,
    unlocked: true,
    color: '#7f1d1d', // Obsidian Crimson Red
    accentColor: '#0f172a',
    soundPitch: 1.45,
  },
  {
    id: 'audi_r8',
    name: 'Audi R8 V10 Plus',
    category: 'supercar',
    description: 'Mid-engine acoustic masterpiece powered by a naturally aspirated 5.2L V10. Features Quattro AWD grip, high carbon side blades, and glass engine canopy.',
    topSpeed: 330,
    acceleration: 96,
    braking: 95,
    handling: 94,
    driftFactor: 0.82,
    weight: 1580,
    price: 24000,
    unlocked: false,
    color: '#eab308', // Vegas Yellow
    accentColor: '#1e293b',
    soundPitch: 1.3,
  },
  {
    id: 'porsche_911',
    name: 'Porsche 911 GT3 RS',
    category: 'supercar',
    description: 'Pure racetrack weapon designed for surgical cornering precision. Features a huge swan-neck rear spoiler wing, front fender vents, and a high-revving flat-six engine.',
    topSpeed: 296,
    acceleration: 94,
    braking: 98,
    handling: 99,
    driftFactor: 0.78,
    weight: 1430,
    price: 38000,
    unlocked: false,
    color: '#22c55e', // Lizard Green
    accentColor: '#0f172a',
    soundPitch: 1.25,
  },
  {
    id: 'lambo_aventador',
    name: 'Lamborghini Aventador SVJ',
    category: 'supercar',
    description: 'V12 carbon-fiber flagship hypercar with aggressive active aerodynamics (ALA), jet-fighter styling cues, center lock wheels, and fire-spitting center exhaust.',
    topSpeed: 350,
    acceleration: 98,
    braking: 96,
    handling: 95,
    driftFactor: 0.90,
    weight: 1525,
    price: 65000,
    unlocked: false,
    color: '#f97316', // Arancio Atlas Orange
    accentColor: '#1e293b',
    soundPitch: 1.4,
  },
];

export const INITIAL_LANDMARKS: Landmark[] = [
  {
    id: 'lm_spire',
    name: 'Skyline Pinnacle Spire',
    district: 'Downtown Financial',
    description: 'The tallest architectural beacon in Solaria Metro, soaring 420 meters above the city.',
    position: { x: 0, y: 1, z: 0 },
    discovered: false,
  },
  {
    id: 'lm_bridge',
    name: 'Marina Suspension Bridge',
    district: 'Bayview Harbor',
    description: 'Twin-tower cable suspension bridge spanning the harbor channel with panoramic ocean views.',
    position: { x: 180, y: 1, z: -80 },
    discovered: false,
  },
  {
    id: 'lm_promenade',
    name: 'Ocean Drive Promenade',
    district: 'Waterfront Beach',
    description: 'Sun-drenched coastal avenue lined with royal palms, Art Deco terraces, and white sand.',
    position: { x: -160, y: 1, z: -140 },
    discovered: false,
  },
  {
    id: 'lm_gardens',
    name: 'Central Plaza Botanical Park',
    district: 'Civic Center',
    description: 'A lush green oasis nestled between glass towers featuring monumental water fountains.',
    position: { x: -80, y: 1, z: 80 },
    discovered: false,
  },
  {
    id: 'lm_docks',
    name: 'Solaria Freight Terminal',
    district: 'Industrial Port',
    description: 'Massive maritime port with gantry cranes, container stacks, and extreme stunt ramps.',
    position: { x: 160, y: 1, z: 160 },
    discovered: false,
  },
];

export const INITIAL_SHOPS: InteractiveShop[] = [
  {
    id: 'shop_tuning',
    name: 'Nitro Customs & Paint Lab',
    category: 'tuning',
    district: 'Commercial District',
    prompt: 'Customize vehicle paint, spoiler, rims and performance upgrades',
    position: { x: -60, y: 0.5, z: -40 },
  },
  {
    id: 'shop_diner',
    name: 'Coastal Horizon Diner & Cafe',
    category: 'diner',
    district: 'Waterfront',
    prompt: 'Grab gourmet snacks and nitro cold brew to restore full stamina and health',
    position: { x: -120, y: 0.5, z: -80 },
  },
  {
    id: 'shop_gas',
    name: 'Apex Supercharge & Pitstop',
    category: 'gas_station',
    district: 'Downtown Outer Loop',
    prompt: 'Instant car repair, full tank refill, and express vehicle wash',
    position: { x: 80, y: 0.5, z: -40 },
  },
  {
    id: 'shop_dealership',
    name: 'Solaria Premier Motor Group',
    category: 'dealership',
    district: 'Downtown Plaza',
    prompt: 'Browse luxury exotic showroom and purchase new unlocked vehicles',
    position: { x: 40, y: 0.5, z: 60 },
  },
  {
    id: 'shop_observation',
    name: 'Vertex Observation Sky Lounge',
    category: 'observation',
    district: 'Downtown Financial',
    prompt: 'Ride high-speed elevator to the panoramic observation deck overlooking the bay',
    position: { x: 0, y: 0.5, z: 20 },
  },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'm_courier',
    title: 'Downtown Courier Dash',
    description: 'Speed-deliver sensitive electronic components to 3 executive locations in Solaria before the timer expires.',
    type: 'courier',
    rewardCash: 1200,
    rewardRep: 80,
    timeLimit: 55,
    checkpoints: [
      { x: -60, z: 20, name: 'Vertex Corporate Tower' },
      { x: 40, z: -100, name: 'Oceanview Suites' },
      { x: 120, z: -40, name: 'Bay Harbor Freight' },
    ],
    currentCheckpointIndex: 0,
    isActive: false,
    isCompleted: false,
  },
  {
    id: 'm_speed_trap',
    title: 'Ocean Drive Speed Trap',
    description: 'Punch the throttle along the straight coastal boulevard and clock over 150 km/h past the speed camera.',
    type: 'speed_trap',
    rewardCash: 1500,
    rewardRep: 100,
    targetSpeed: 150,
    checkpoints: [
      { x: -140, z: -120, name: 'Ocean Drive Radar Gantry' },
    ],
    currentCheckpointIndex: 0,
    isActive: false,
    isCompleted: false,
  },
  {
    id: 'm_drift',
    title: 'Port Solaria Drift King',
    description: 'Tear up the asphalt around the industrial docks and chain 1,200 drift points in high-slip slides.',
    type: 'drift',
    rewardCash: 1800,
    rewardRep: 120,
    targetScore: 1200,
    checkpoints: [
      { x: 140, z: 120, name: 'Docks Hairpin Circuit' },
    ],
    currentCheckpointIndex: 0,
    isActive: false,
    isCompleted: false,
  },
  {
    id: 'm_tourist',
    title: 'Solaria Grand Tour',
    description: 'Cruise to 3 scenic landmarks across the city to photograph the skyline and coastal vistas.',
    type: 'tour',
    rewardCash: 2000,
    rewardRep: 150,
    checkpoints: [
      { x: 0, z: 0, name: 'Skyline Pinnacle Spire' },
      { x: 180, z: -80, name: 'Marina Suspension Bridge' },
      { x: -80, z: 80, name: 'Central Plaza Gardens' },
    ],
    currentCheckpointIndex: 0,
    isActive: false,
    isCompleted: false,
  },
];

export const HIDDEN_TOKENS = [
  { id: 'tok_1', x: -35, y: 1.2, z: -25, collected: false },
  { id: 'tok_2', x: 85, y: 1.2, z: -95, collected: false },
  { id: 'tok_3', x: 145, y: 2.5, z: 145, collected: false },
  { id: 'tok_4', x: -145, y: 1.2, z: -160, collected: false },
  { id: 'tok_5', x: -75, y: 1.2, z: 95, collected: false },
  { id: 'tok_6', x: 25, y: 1.2, z: 135, collected: false },
  { id: 'tok_7', x: -110, y: 1.2, z: -20, collected: false },
  { id: 'tok_8', x: 190, y: 3.0, z: -70, collected: false },
  { id: 'tok_9', x: 5, y: 1.2, z: -140, collected: false },
  { id: 'tok_10', x: -60, y: 1.2, z: 140, collected: false },
];
